### ISSUE TITLE
Helper methods from radbear_multi_tenant likely missing

### ISSUE THREAD

**Issue by plicjo** [radicalbear/rad_hoc_rails#1]
https://github.com/radicalbear/rad_hoc_rails/blob/master/app/decorators/rad_hoc_rails/rad_hoc_query_decorator.rb#L54 will probably blow up because these methods live in radbear_multi_tenant

A simple integration test of the RadHocQueriesController#run endpoint will tell the tale.

**Comment by garyfoster** [comment]
this has been resolved by adding a helper method to the rad_hoc_queries controller but we'll probably want to change this when we work on name-spacing everything

**Comment by garyfoster** [comment]
There are integration tests that require methods such as `format_datetime` to be there and they run fine whether or not we have the `helper RadHocRails::ApplicationHelper` line in the rad_hoc_queries_controller. However, this line is required for other apps to run properly. Curious..

**Comment by plicjo** [comment]
I stubbed out the methods in the decorator tests, which depend on those methods in the helper.

I didn't think that would be an issue, but if I unstub them, those tests will break. That's a good thing since this stuff is no longer inside of Groundswell

**Comment by plicjo** [comment]
I assigned this to myself in Groundswell.
