### ISSUE TITLE
Allow using of predefined scopes for filtering records

### ISSUE THREAD

**Issue by elbzero** [radicalbear/rad_hoc_rails#11]
When creating a query it would be helpful to have the ability to expose rails predefined scopes to reuse as a filter for the current query, so that we can save the user time from recreating common filters. 

We would probably would not want to expose all scopes, as some scopes may only be needed in internal coding, but instead allow a list of scopes to be configured for access on the query interface.

**Comment by plicjo** [comment]
Logged in Groundswell.
