### ISSUE TITLE
Allow filter values to be changed dynamically when query results

### ISSUE THREAD

**Issue by elbzero** [radicalbear/rad_hoc_rails#12]
When creating a filter it would be helpful to allow the option to prompt the user for a value when viewing the results of the query. 

This would allow the user to change the values of the filter during viewing the results which would make the query useful for different purposes without having to edit or create a new query.

**Comment by plicjo** [comment]
That would be awesome. Ideally, we would pull the Run table functionality into the Ember app so that we can re-use the UI components

**Comment by plicjo** [comment]
Logged in Groundswell.
