### ISSUE TITLE
Give associated tables the option to use outer join or include

### ISSUE THREAD

**Issue by elbzero** [radicalbear/rad_hoc_rails#15]
Not sure if this is a bug or an enhancement request but when I include an associated table it is automatically an inner join. This will not return a row when associated foreign keys are null

**Comment by garyfoster** [comment]
I think this would be tricky if we allow a mix, perhaps we can allow all outers or all inners. Better yet, how about we always do outer joins, and then when the user wants to limit data like an inner join, they do a not-null filter on the fk. That would probably be most intuitive to the user.

**Comment by plicjo** [comment]
Closing, because we have a task for this in Groundswell.
