### ISSUE TITLE
current_user helper not installing to application_controller if subclassed

### ISSUE THREAD

**Issue by garyfoster** [radicalbear/rad_hoc_rails#6]
The installer injects some code into application_controller, and it uses `after: "ActionController::Base"` for the injection position. If the application_controller is subclassed, then that search fails and the snippet is not injected. Workaround for now is to add the rad_hoc_user method and helper method manually.

**Comment by plicjo** [comment]
Closing this as we will be pulling Rad Hoc back into Groundswell.
