### ISSUE TITLE
requires stubbing check_tenant in application_controller

### ISSUE THREAD

**Issue by garyfoster** [radicalbear/rad_hoc_rails#7]
The app where rad hoc originated required calling a method named `check_tenant` in a `before_filter` in application controller. This line is currently in the source code and for sites not using it, you need to stub out this method as per the comments in the initializer. This is super wonky and should eventually be abstracted out properly.

**Comment by plicjo** [comment]
Closing this as we will be pulling Rad Hoc back into Groundswell.
