### ISSUE TITLE
requires stubbing acts_as_tenant in RadHocQuery model

### ISSUE THREAD

**Issue by garyfoster** [radicalbear/rad_hoc_rails#8]
The app where rad hoc originated required calling a call to `acts_as_tenant` in the `RadHocQuery` model. This line is currently in the source code and for sites not using it, you need to stub out this method as per the comments in the initializer. This is not-at-all-baller and should eventually be abstracted out properly.

**Comment by plicjo** [comment]
Closing, as we will be pulling this back into Groundswell.
